spring:
  application:
    name: user-center
  # DataSource Config
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.106.139.132:3306/user_center
    username: haihai
    password: jianghai123
  # session失效时间
  session:
    timeout: 86400

